#
# Paths
#
path_prefix:
  - /storage1/fs1/thomas.k/Active
  - Z:\Active
  - /Volumes/Active
  - /home/skim/ris_share/Active
  - /mnt/Act~ive

project_path: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM

## Use the list of all WPEs extracted from Clarity.
wpe_list: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/wpe_list/240910_all_inpatient_wpes_190101_240601_sorted.csv
action_token_map_path: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/wpe_list/action_token_map.json


results_path: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/results
  # icu_ehr_logs/EHR_audit_log_LLM/results

audit_log_path: AHRQ_Access_Logs_and_WPEs/processed_data/anonymize_derek_pull/update_2408
  #Sample path: AHRQ_Access_Logs_and_WPEs/processed_data/anonymize_derek_pull/debug
  #Actual path: AHRQ_Access_Logs_and_WPEs/processed_data/anonymize_derek_pull/update_2408

## Filename formatted as {XX}_logs_IDENTIFIED.parquet, with {XX} being the numerical error index extracted from Clarity.
audit_log_file: _logs_IDENTIFIED.parquet

audit_log_cache: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/data
                  # For full dataset: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/data
                  # Mini dataset (all WPEs, 1 to 10 matching): AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/data_1to10_matched_controls
                  # Debugging dataset (100 WPEs, 1 to 1 matching): AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/data_debug
#  Directory structure:
#    ../data OR ../data_1to10_matched_controls OR ../data_debug
#     +--{idx}
#       +--case_controls
#         +--{idx}_case_1h.parquet
#         +--{idx}_control_1h.parquet

model_cache_path: AHRQ_Access_Logs_and_WPEs/EHR_audit_log_LLM/cache/models/cache_
  #TODO: update code accordingly
  # icu_ehr_logs/EHR_audit_log_LLM/cache/cache_

audit_log_cache_file: # match time window to the min_prior parameter in line 59
  case: _case_30m.parquet
  control: _control_30m.parquet


#
# HuggingFace Model Repo
#
HF_model_name: llama3-WPE_EHRlogs-WB-FBeval-T3 # Local directory name that will save the model
HF_repo_name: llama3-WPE_EHRlogs-WB-FBeval-T3 # HF repo name that will save the model
load_from_HF: False # if True, load from HF repo. if False, load from local checkpoint directory.
peft_is_trainable: False # required when load_from_HF=True; set False for inference, set True to continue training.
resume_training: False

# If a number N (float or int) is specified, "autogenerated actions" that are <N seconds apart will not be considered for inference metric calculation
timedelta_cutoff:

# Set to True if you want reset cached data, i.e., load & process the data from scratch.
reset_cache: False

# Set to True onlly if you want to build a static feature set with the data split setup. Only works with reset_cache=True
cache_static_features: False

# Set to True to log and monitor progress in Weights and Biases (W&B) for actual runs, set to False for debugging
log_wandb: True

# If using custom tokenization (1 token per METRIC_NAME)
custom_tokenization: False

use_prompt: True   # False for baseline,  True for experiment
# Choose how many tokens to skip in the beginning of each input sequence for calculating inference-phase metrics
skip_N_tokens: 10
use_delimiter: True # must set to true for word-based tokenization approach, when evaluating field-level accuracy instead of default next-token accuracy.

#
# Data preprocessing
#
## Choose the fields to keep from audit logs table.
num_fields: 1
  # Default 4 (same as previous paper; USER_ID, time_delta, PAT_ID,  METRIC_NAME|REPORT_NAME)
  # Specify 3 to only keep (USER_ID, TIME_DELTA, METRIC_NAME|REPORT_NAME)
  # Specify 1 to only keep a single column METRIC_NAME|REPORT_NAME
  # Optionally specify 5, to additionally have "session_ID" as an augmented field.

# (DEBUG) use a mini sample of data (i.e., use n WPE cases)
n_mini: 3000

temporal_distinct_testset:

# Option to sample n controls per each case.
sample_n_controls:

## Unit string to be considered as a single sentence. Options: session, row, all.
  # Specify 'all' to use the entire n-minutes sequence preceding order.
unit_string: all

## if unit_string is set to "all", this parameter must be specified and will determine
  # the time window of audit log action sequences that the model will be trained on
min_prior: 30

# Option to keep raw tabular cell values or map them into simpler categories (options: numbers, words)
# Note: current implementation only works when num_fields > 1 (i.e., USER_ID field must not be discarded)
convert_field_vals_to:





exclusion_list: # Leave is as blank for now
## Legacy feature: Whether to perform noise removal (auto-generated actions)
clean_auditLogs: False
sep_min:
#  shift: 360
  session: 5 # minutes

random_seed: 141837
train_split: 0.7
val_split: 0.1

# Legacy feature: timestamp_bins; Current version keeps raw timedelta values (seconds)
#  spacing: logspace
#  min: 0
#  max: 240
#  bins: 5

#
# Experiment
#
experiment: SFTpipeline #SFTtrain
  # Options:
    #demo_train #demo_test #demo_SFTtrain #mapping #demo_train #demo_LinPred #blora #train_test #demo_blora #train #demo_blora #train #train_test #demo #2 #demo #2 #demo



# Use only if launching the script with a single process (e.g., python main_WPE.py) instead of a torchrun command
# If you want to specify a GPU ID that you want to run the pipeline on, populate this parameter.
GPU_ID:
  # Options
  # RIS T3: [0,1,2]
  # SRI CSL: as available
  # specify "auto" for model parallelism (not data parallelism).

# Specify number of workers. Set to"dynamic" to utilize all available CPU cores. Decrease it to reduce the load on shared memory.
num_workers: 1
provider_type:
  # Options: Attending,APP, or leave it blank to keep all user types.
use_vanilla: False
search: greedy
  # Options: greedy (default), beam, contrastive
custom_loss: False # if True, use CE_loss + weight * Levenstein_Loss
custom_loss_w: 0.1
dynamic_w: False # if True, increase custom_loss_w by 0.05 on every epoch.

debug: False
format_results: True
ignore_warnings: True

save_model_at: local #HF
  # Options: local or HF
    # local: save the entire model weights on the model_cache_path (large due to entire model weights)
    # HF: save the LoRA fine-tuned model weights on HF under HF_username/HF_model_name
load_format: safetensors
  # Options: pt or safetensors
    # pt: old LM pipeline saves fine-tuned model locally in .pt file
    # safetensors: new SFTTrainer pipeline saves fine-tuned model locally in .safetensors file



#
# Model
#
model: meta-llama/Meta-Llama-3-8B #meta-llama/Llama-2-7b-hf #meta-llama/Meta-Llama-3-8B
  # Options:
    # meta-llama/Meta-Llama-3-8B: trained on a general language modeling objective
    # meta-llama/Meta-Llama-3-8B-Instruct: fine-tuned on specific tasks to follow instructions, better suited for prompting
    # facebook/multi-token-prediction: awaiting access to HF repo
    # meta-llama/Llama-2-7b-hf: similar alternative to Llama-3-8B
model_configs:
  meta-llama/Meta-Llama-3-8B:
    n_positions: 512 #256 # If a CUDA memory error occurs, reduce n_positions or batch_size.
    prompt_reserved_tokens: 64 # Can modify later, based on how long your prompt & static info (i.e., pat ID or user ID context) is, at the beginning of the input string.
  meta-llama/Meta-Llama-3-8B-Instruct:
    n_positions: 128 # If a CUDA memory error occurs, reduce n_positions or batch_size.
  meta-llama/Llama-2-7b-hf:
    n_positions: 128 # (n_pos=128, batch_size=160): peak ~30GB GPU memory

# The batch size determines how many samples are processed together in one iteration.
# It is recommended to use the largest batch size that fits into the GPU memory to optimize training speed.
# If a CUDA memory error occurs, reduce the batch size.
batch_size:
  train: 48 #150 #200 #32
  val: 48 #150
  test: 16 #150

lr: 0.0005 # default 0.00005
# 2 epochs usually enough to fine tune.
epochs: 4


# Whether to quantize the model prior to applying PEFT LoRA.
# QLoRA will be performed when set to True. LoRA when set to False.
# Most benefit in terms of reduced GPU memory when used with AdamW optimizer.
use_quant: True

# LoRA config
peft_config:
  r: 8 # default 8. TODO: May want to increase it?
  lora_alpha: 16 # default 16
  target_modules: ["q_proj", "v_proj"]
  lora_dropout: 0.05 # default 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
optimizer_type: AdamW
  # Options: SGD, Adagrad, Adadelta, RMSprop, AdamW
loss_reduction: mean
optional_optimization: False # whether to perform additional optimization such as mixed precision scaling or gradient accumulation.

gradient_accumulation_steps: 2

save_model_when:
  option: best
    # Options:
      # best: DEFAULT -- save model with best validation performance
      # epoch: DEPRECATED -- after every P epoch (specify P through "period" parameter below)
  period: 1
token_padding_side: right
  # Options: left or right
  # Set to 'left' when using decoder-only architecture, while 'right' is generally preferred with autoregressive models.







